### ISSUE TITLE
where is "datasets" at "from datasets import load_dataset" of "/ef_knnlm/adaptive_retrieval/adaptive_retrieval.py"

### ISSUE THREAD

**Issue by Huisw** [jxhe/efficient-knnlm#1]
## 🐛 Bug

bash ef_knnlm/adaptive_retrieval/train_ar.sh

Traceback (most recent call last):
  File "ef_knnlm/adaptive_retrieval/adaptive_retrieval.py", line 13, in <module>
    from datasets import load_dataset
ImportError: cannot import name 'load_dataset' from 'datasets' (unknown location)

how to get "datasets"?

**Comment by jxhe** [comment]
I think you can just run `pip install datasets`
