### ISSUE TITLE
Question regarding kNN-LM (exact)

### ISSUE THREAD

**Issue by jiaqing23** [jxhe/efficient-knnlm#2]
In the Efficient kNN-LM paper, the result of  kNN-LM (exact) is included (with ppl = 16.12, and very slow inference speed). I checked the original kNN-LM (Khandelwal, 2020) and the ppl score is matched with it.

![image](https://user-images.githubusercontent.com/14024143/217468096-f287f647-3734-474f-9784-521f11bdac36.png)

May I know how to you obtain the score for kNN-LM (ppl = 16.65), which part of the code did you change from their original repo (https://github.com/urvashik/knnlm) and make the inference speed increase? What is the different between kNN-LM and kNN-LM (exact)? Because the original kNN-LM paper doesn't have any result of ppl = 16.65. 

Thank you very much!

**Comment by jxhe** [comment]
As their README says, you can set `--no-load-keys` and `--knn-sim-func "do_not_recomp_l2"`
<img width="744" alt="Screenshot 2023-02-08 at 5 13 56 PM" src="https://user-images.githubusercontent.com/18393447/217486275-67c2c465-a1b6-4333-858b-f6734fa4253d.png">

**Comment by jiaqing23** [comment]
Thanks for the response!
